# Generated by Django 6.1.1 on 2026-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='System', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Applied'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed Application')], db_index=True, default='ACTIVE', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('backup_dir', models.CharField(blank=True, default='', max_length=500)),
                ('files_modified', models.JSONField(default=list)),
                ('manifest_data', models.JSONField(default=dict)),
                ('applied_by', models.CharField(default='system', max_length=100)),
            ],
            options={
                'verbose_name': 'System Hot-Patch',
                'verbose_name_plural': 'System Hot-Patches',
                'ordering': ['-applied_at'],
            },
        ),
    ]
