# Generated by Django 5.2.17 on 2026-09-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0003_assistantsession_alter_aipromptconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
            ],
            options={
                'verbose_name': 'AI Prompt Configuration',
                'verbose_name_plural': 'AI Prompt Configurations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automation.aipromptconfig',),
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant Message',
                'verbose_name_plural': 'Assistant Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automation.assistantmessage',),
        ),
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant Session',
                'verbose_name_plural': 'Assistant Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automation.assistantsession',),
        ),
    ]
