# Generated by Django 6.1.1 on 2026-09-07 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0010_savedprofile_cookie_count_savedprofile_cookies_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('seed_keywords', models.JSONField(default=list, help_text='List of search phrases, e.g. ["budget mechanical keyboards", "OLED monitor test"]')),
                ('seed_websites', models.JSONField(default=list, help_text='List of authority domains, e.g. ["rtings.com", "theverge.com"]')),
                ('target_youtube_channels', models.JSONField(default=list, help_text='Channels to engage with, e.g. ["@MKBHD", "@Dave2D"]')),
                ('blacklist_keywords', models.JSONField(default=list, help_text='Keywords to avoid, e.g. ["controversial", "nsfw"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('WARMING', 'Cookie Warmer (General Web)'), ('YOUTUBE', 'YouTube Operations'), ('BLOG', 'Blog / Content Reading'), ('TWITTER', 'X / Twitter'), ('CUSTOM', 'Custom Automation')], default='YOUTUBE', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.niche')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maturation_stage', models.CharField(choices=[('INFANT', 'Infant (Fresh Profile, 0-25)'), ('SEEDING', 'Seeding (Basic Tracker Cookies, 26-50)'), ('MATURING', 'Maturing (Niche Browsing History, 51-75)'), ('MATURE', 'Mature / Battle-Tested (76-100)')], default='INFANT', max_length=20)),
                ('unique_domains_visited', models.IntegerField(default=0)),
                ('patience_index', models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('engagement_rate', models.FloatField(default=0.15, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)])),
                ('typing_wpm', models.IntegerField(default=65, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)])),
                ('typo_probability', models.FloatField(default=0.03, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.15)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='devices.savedprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecutionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'Dispatched to Device'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STALLED', 'Stalled')], default='PENDING', max_length=20)),
                ('entry_state_id', models.CharField(default='start', max_length=100)),
                ('compiled_dag', models.JSONField(default=dict)),
                ('current_state_id', models.CharField(default='start', max_length=100)),
                ('execution_context', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='devices.savedprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationtask')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileNicheAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_percentage', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_affiliations', to='automation.niche')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niche_affiliations', to='devices.savedprofile')),
            ],
            options={
                'unique_together': {('profile', 'niche')},
            },
        ),
    ]
