# Generated by Django 6.1.1 on 2026-09-07 20:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Recovery Decision Engine', max_length=100)),
                ('provider', models.CharField(choices=[('OPENROUTER', 'OpenRouter.ai'), ('GEMINI', 'Google Gemini')], default='OPENROUTER', max_length=30)),
                ('model_name', models.CharField(default='deepseek/deepseek-chat', help_text='Model identifier, e.g. gemini-2.5-flash, deepseek/deepseek-chat, anthropic/claude-3.5-haiku', max_length=150)),
                ('temperature', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('system_prompt', models.TextField(default='You are GhostPilot, an autonomic browser recovery controller.\nContext:\n- Task Name: {task_name} ({task_category})\n- Stalled State ID: {current_state}\n- Execution Context: {execution_context}\n\nThe mobile browser profile is currently stuck or received an unexpected page state.\nAnalyze the provided stripped DOM representation and optional screenshot to deduce a concrete physical recovery action.\n\nRules:\n1. If an unexpected popup, cookie banner, or consent wall is present, target its dismiss/accept button via TAP_COORDINATES using center X/Y bounds.\n2. If a video is paused or has an active ad skip button, target playback or skip controls.\n3. If the page is blank or scrolled to bottom, return BÉZIER_SWIPE with direction DOWN.\n4. If you can deduce which DAG node to resume, set next_state_override.\n5. Provide concise reasoning.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
