# Generated by Django 5.2.17 on 2026-09-07 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_aipromptconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aipromptconfig',
            options={'verbose_name': 'AI Prompt Configuration', 'verbose_name_plural': 'AI Prompt Configurations'},
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool Output'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_calls', models.JSONField(blank=True, help_text='Stored tool invocations requested by the LLM', null=True)),
                ('tool_call_id', models.CharField(blank=True, default='', help_text='For OpenRouter tool responses, maps to the original tool_call.id', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='automation.assistantsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
