# Generated by Django 6.1.1 on 2026-09-11 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_assistantsession_alter_aipromptconfig_options_and_more'),
        ('devices', '0011_alter_savedprofile_proxy_pass_browserstorage_and_more'),
        ('executions', '0002_execution_executionevent_executionlease_acquired_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecutionqueue',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='compiled_dag',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='current_state_id',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='entry_state_id',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='execution_context',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='taskexecutionqueue',
            name='status',
        ),
        migrations.AddField(
            model_name='taskexecutionqueue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskexecutionqueue',
            name='execution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_entry', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='taskexecutionqueue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_dispatches', to='devices.savedprofile'),
        ),
        migrations.AlterField(
            model_name='taskexecutionqueue',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_dispatches', to='automation.automationtask'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionqueue',
            index=models.Index(fields=['profile', 'created_at'], name='automation__profile_67bb58_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionqueue',
            index=models.Index(fields=['task', 'created_at'], name='automation__task_id_34d315_idx'),
        ),
    ]
