# Generated by Django 6.1.1 on 2026-09-13 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_taskexecutionqueue_options_and_more'),
        ('devices', '0012_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('schedule_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('DAILY', 'Daily'), ('INTERVAL', 'Interval')], default='DAILY', max_length=20)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('selection_mode', models.CharField(choices=[('EXPLICIT_PROFILES', 'Explicit Profiles'), ('NICHE', 'Niche'), ('ALL_ELIGIBLE', 'All Eligible')], default='NICHE', max_length=30)),
                ('concurrency_limit', models.PositiveIntegerField(default=5)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('max_runtime_seconds', models.PositiveIntegerField(default=1800)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('failure_threshold_percent', models.PositiveIntegerField(default=30)),
                ('priority', models.IntegerField(default=10)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_niches', models.ManyToManyField(blank=True, related_name='automations', to='automation.niche')),
                ('target_profiles', models.ManyToManyField(blank=True, related_name='automations', to='devices.savedprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='automation.automationtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_key', models.CharField(db_index=True, max_length=255)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('total_target_profiles', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('dispatched_count', models.PositiveIntegerField(default=0)),
                ('running_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('stalled_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('automation', 'run_key')},
            },
        ),
    ]
