# Generated by Django 5.2.17 on 2026-09-15 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_automation_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='workflow_type',
            field=models.CharField(default='SEARCH_AND_DISCOVER', max_length=50),
        ),
        migrations.AlterField(
            model_name='automationtask',
            name='category',
            field=models.CharField(choices=[('WARMING', 'Cookie Warmer (General Web)'), ('YOUTUBE', 'YouTube Operations'), ('WEBSITE', 'Website / Direct Traffic'), ('FACEBOOK', 'Facebook Operations'), ('TWITTER', 'X / Twitter'), ('TIKTOK', 'TikTok Operations'), ('REDDIT', 'Reddit Operations'), ('BLOG', 'Blog / Content Reading'), ('CUSTOM', 'Custom Automation')], default='YOUTUBE', max_length=20),
        ),
    ]
