# Generated by Django 5.2.17 on 2026-09-23 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_automationtask_owner_automationtask_workflow_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, default='YOUTUBE', max_length=50)),
                ('device_model', models.CharField(blank=True, default='default', max_length=100)),
                ('viewport_width', models.IntegerField(default=1080)),
                ('viewport_height', models.IntegerField(default=2400)),
                ('anchors', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('screenshot_base64', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
