# Generated by Django 5.2.17 on 2026-09-24 00:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_platformcalibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Workflow', max_length=255)),
                ('platform', models.CharField(db_index=True, default='YOUTUBE', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('journeys', models.JSONField(blank=True, default=list, help_text='List of journeys and their sequential action steps')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
