# Generated by Django 5.2.17 on 2026-09-24 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_customworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('category', models.CharField(db_index=True, default='workflow', max_length=50)),
                ('platform', models.CharField(db_index=True, default='YOUTUBE', max_length=50)),
                ('author', models.CharField(blank=True, default='Antidetect Team', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Puzzle', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('package_file', models.FileField(blank=True, null=True, upload_to='addons_packages/')),
                ('installed_dir', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
