# Generated by Django 6.1.1 on 2026-09-11 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0011_alter_savedprofile_proxy_pass_browserstorage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RELEASED', 'Released')], db_index=True, default='ACTIVE', max_length=20)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='devices.savedprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='executions__profile_827811_idx'), models.Index(fields=['device_id', 'status'], name='executions__device__8d42bf_idx')],
            },
        ),
    ]
