# Generated by Django 6.1.1 on 2026-09-11 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_assistantsession_alter_aipromptconfig_options_and_more'),
        ('devices', '0011_alter_savedprofile_proxy_pass_browserstorage_and_more'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'Dispatched to Device'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STALLED', 'Stalled')], db_index=True, default='PENDING', max_length=20)),
                ('entry_state_id', models.CharField(default='start', max_length=100)),
                ('current_state_id', models.CharField(default='start', max_length=100)),
                ('compiled_dag', models.JSONField(default=dict)),
                ('execution_context', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('RUN_STARTED', 'Run Started'), ('STATE_CHANGED', 'State Changed'), ('HEARTBEAT', 'Heartbeat'), ('STALLED', 'Execution Stalled'), ('SUCCESS', 'Execution Succeeded'), ('FAILED', 'Execution Failed'), ('ABORTED', 'Execution Aborted'), ('AI_DECISION', 'AI Decision'), ('AI_RECOVERY', 'AI Recovery Executed'), ('COOKIE_IMPORTED', 'Cookie Imported'), ('BUTTON_CLICKED', 'Button Clicked')], db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='executionlease',
            name='acquired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='executionlease',
            name='execution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='executionlease',
            index=models.Index(fields=['execution_id', 'status'], name='executions__executi_1d667d_idx'),
        ),
        migrations.AddField(
            model_name='execution',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_executions', to='devices.savedprofile'),
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='automation.automationtask'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['execution_id', 'created_at'], name='executions__executi_c32e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['event_type', 'created_at'], name='executions__event_t_c9b383_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['profile', 'status'], name='executions__profile_4b1702_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['task', 'status'], name='executions__task_id_4faf3c_idx'),
        ),
    ]
