# Generated by Django 6.1.1 on 2026-09-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_taskexecutionqueue_options_and_more'),
        ('devices', '0011_alter_savedprofile_proxy_pass_browserstorage_and_more'),
        ('executions', '0002_execution_executionevent_executionlease_acquired_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='executionevent',
            name='executions__executi_c32e1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='executionlease',
            name='executions__executi_1d667d_idx',
        ),
        migrations.RemoveField(
            model_name='executionevent',
            name='execution_id',
        ),
        migrations.RemoveField(
            model_name='executionlease',
            name='execution_id',
        ),
        migrations.AddField(
            model_name='executionevent',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='executionlease',
            name='execution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='executions.execution'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='devices.savedprofile'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationtask'),
        ),
        migrations.AddIndex(
            model_name='executionevent',
            index=models.Index(fields=['execution', 'created_at'], name='executions__executi_c32e1f_idx'),
        ),
    ]
