# Generated by Django 6.1.1 on 2026-09-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device'),
        ('executions', '0003_remove_executionevent_executions__executi_c32e1f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlease',
            name='registered_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='devices.device'),
        ),
    ]
