# Generated by Django 6.1.1 on 2026-09-13 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_automation_automationrun'),
        ('devices', '0012_device'),
        ('executions', '0004_executionlease_registered_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('compiler_version', models.CharField(default='v2.0.0', max_length=50)),
                ('compiled_dag', models.JSONField(default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='automation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.automationrun'),
        ),
        migrations.AddField(
            model_name='execution',
            name='checkpoint_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='last_confirmed_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='execution',
            name='last_confirmed_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='last_transition_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='execution',
            name='max_retries',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='execution',
            name='plan_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='execution',
            name='recovery_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RESOLVED', 'Resolved'), ('EXHAUSTED', 'Exhausted')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='execution',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='executionlease',
            index=models.Index(fields=['profile', 'status', 'expires_at'], name='executions__profile_527fe7_idx'),
        ),
        migrations.AddField(
            model_name='executionplan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='automation.automationtask'),
        ),
        migrations.AddField(
            model_name='execution',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='executions.executionplan'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['automation_run', 'status'], name='executions__automat_be645d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executionplan',
            unique_together={('task', 'version')},
        ),
    ]
