# Generated by Django 5.2.17 on 2026-09-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_executionplan_execution_automation_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'Dispatched to Device'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STALLED', 'Stalled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
