# Generated by Django 6.1.1 on 2026-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_android_version_device_battery_percent_and_more'),
        ('executions', '0006_alter_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='cancel_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='executionlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('profile',), name='uniq_active_lease_per_profile'),
        ),
    ]
