# Generated by Django 6.1.1 on 2026-09-06 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('model_code', models.CharField(max_length=100)),
                ('android_version', models.IntegerField(default=14)),
                ('soc', models.CharField(max_length=150)),
                ('webgl_vendor', models.CharField(max_length=100)),
                ('webgl_renderer', models.CharField(max_length=150)),
                ('ram_gb', models.IntegerField(default=8)),
                ('cpu_cores', models.IntegerField(default=8)),
                ('screen_width', models.IntegerField(default=384)),
                ('screen_height', models.IntegerField(default=854)),
                ('dpr', models.FloatField(default=2.8125)),
                ('user_agent', models.TextField()),
                ('proxy_type', models.CharField(default='DIRECT', max_length=20)),
                ('proxy_host', models.CharField(blank=True, default='', max_length=255)),
                ('proxy_port', models.IntegerField(default=0)),
                ('proxy_user', models.CharField(blank=True, default='', max_length=100)),
                ('proxy_pass', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
