# Generated by Django 6.1.1 on 2026-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini (gemini-2.5-flash)'), ('openrouter', 'OpenRouter.ai (Claude, GPT-4o, Gemini, DeepSeek)')], default='gemini', help_text='Select AI provider for device fingerprint generation', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key (leave blank to read from environment variable GEMINI_API_KEY or OPENROUTER_API_KEY)', max_length=255)),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='Target model ID. For Gemini: gemini-2.5-flash. For OpenRouter: google/gemini-2.5-flash, anthropic/claude-3.5-haiku, openai/gpt-4o-mini', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM & API Configuration',
                'verbose_name_plural': 'LLM & API Configurations',
            },
        ),
    ]
