# Generated by Django 6.1.1 on 2026-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_llmconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Optional default model ID (leave blank to allow direct dynamic selection from the provider)', max_length=150),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter.ai')], default='gemini', help_text='Select AI provider for device fingerprint generation', max_length=20),
        ),
    ]
