# Generated by Django 6.1.1 on 2026-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_llmconfig_model_name_alter_llmconfig_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('singleton_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('max_active_profiles', models.IntegerField(default=5)),
                ('force_global_mute', models.BooleanField(default=True)),
                ('default_video_resolution', models.CharField(default='240p', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
