# Generated by Django 6.1.1 on 2026-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='selected_ai_model',
            field=models.CharField(default='google/gemini-2.0-flash-001', max_length=150),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='selected_ai_provider',
            field=models.CharField(default='openrouter', max_length=50),
        ),
    ]
