# Generated by Django 6.1.1 on 2026-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_globalsetting_selected_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='saved_gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=150),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='saved_openrouter_model',
            field=models.CharField(default='google/gemini-2.0-flash-001', max_length=150),
        ),
    ]
