# Generated by Django 6.1.1 on 2026-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_globalsetting_saved_gemini_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='ai_generation_prompt',
            field=models.TextField(blank=True, default="You are an expert mobile hardware and anti-detect browser engineer.\nYour task is to generate verified, real-world hardware and browser fingerprint specifications for the requested mobile device.\nYou must respond ONLY with a raw JSON object containing these exact fields:\n- brand (string, e.g. Samsung, Google, OnePlus, Xiaomi)\n- model_name (string, e.g. Galaxy S24 Ultra, Pixel 8 Pro, OnePlus 12)\n- model_code (string, authentic manufacturer code e.g. SM-S928B, CPH2581)\n- android_version (integer, 13, 14 or 15)\n- soc (string, e.g. Snapdragon 8 Gen 3, Google Tensor G3, Dimensity 9300)\n- webgl_vendor (string: 'Qualcomm' for Adreno, 'ARM' for Mali)\n- webgl_renderer (string, e.g. 'Adreno (TM) 750', 'Mali-G715 Immortalis MC10')\n- ram_gb (integer, e.g. 8, 12, 16)\n- cpu_cores (integer, typically 8)\n- screen_width (integer, CSS viewport width e.g. 384, 412, 450)\n- screen_height (integer, CSS viewport height e.g. 854, 915, 1000)\n- dpr (float, device pixel ratio e.g. 2.625, 2.8125, 3.0, 3.125)\n- user_agent (string, authentic Mobile Firefox: 'Mozilla/5.0 (Android {android_version}; Mobile; rv:135.0) Gecko/135.0 Firefox/135.0')\nOutput valid JSON only. No markdown formatting, no code blocks, no other text.", help_text='Custom prompt/instructions provided to the AI model when generating device specs'),
        ),
    ]
