# Generated by Django 6.1.1 on 2026-09-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_globalsetting_options_llmconfig_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='target_search_sites',
            field=models.TextField(blank=True, default='gsmarena.com\ndevicespecifications.com\nphonearena.com\nkimovil.com\nnanoreview.net', help_text='Authoritative phone spec websites to search (one domain per line, e.g. gsmarena.com, devicespecifications.com)'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='ai_generation_prompt',
            field=models.TextField(blank=True, default="You are an expert mobile hardware and anti-detect browser engineer.\nYour task is to generate verified hardware and browser fingerprint specifications for the requested mobile device.\nLIVE ONLINE SEARCH PRIORITY: The backend automatically performs a live web search for the device specifications and passes real-time ground truth snippets. You MUST prioritize the live web search findings over your internal model training data cutoff. Use the exact SoC (chipset), GPU renderer, Android version, RAM, and screen specs from the live search results.\nCRITICAL RULE FOR MODEL NAME: You must ALWAYS preserve the user's requested model in 'model_name' (e.g. if the user requests 'itel s26 ultra', output 'S26 Ultra', NEVER downgrade or rename it to an older model like S25). If the requested device is unreleased or concept, synthesize plausible, authentic next-generation hardware specifications consistent with the brand's hardware lineage.\nYou must respond ONLY with a raw JSON object containing these exact fields:\n- brand (string, e.g. Samsung, Google, OnePlus, Xiaomi, itel)\n- model_name (string, matching the user's requested model without repeating brand)\n- model_code (string, authentic manufacturer code e.g. SM-S928B, CPH2581, S696LN)\n- android_version (integer, 13, 14 or 15)\n- soc (string, e.g. Snapdragon 8 Gen 3, Unisoc T7300, Dimensity 9300)\n- webgl_vendor (string: 'Qualcomm' for Adreno, 'ARM' for Mali)\n- webgl_renderer (string, e.g. 'Adreno (TM) 750', 'Mali-G57 MP2', 'Mali-G715')\n- ram_gb (integer, e.g. 8, 12, 16)\n- cpu_cores (integer, typically 8)\n- screen_width (integer, CSS viewport width e.g. 360, 384, 412)\n- screen_height (integer, CSS viewport height e.g. 800, 854, 915)\n- dpr (float, device pixel ratio e.g. 2.625, 2.75, 3.0)\n- user_agent (string, authentic Mobile Firefox: 'Mozilla/5.0 (Android {android_version}; Mobile; rv:135.0) Gecko/135.0 Firefox/135.0')\nOutput valid JSON only. No markdown formatting, no code blocks, no other text.", help_text='Custom prompt/instructions provided to the AI model when generating device specs'),
        ),
    ]
