# Generated by Django 6.1.1 on 2026-09-07 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_globalsetting_target_search_sites_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprofile',
            name='cookie_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='cookies_data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='device_sync_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='history_data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='last_used_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='tabs_data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='tag',
            field=models.CharField(blank=True, default='Default', max_length=50),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='web_rtc_mode',
            field=models.CharField(blank=True, default='Mdns', max_length=50),
        ),
    ]
