# Generated by Django 6.1.1 on 2026-09-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_savedprofile_cookie_count_savedprofile_cookies_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedprofile',
            name='proxy_pass',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BrowserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_data', models.TextField(blank=True, default='[]')),
                ('history_data', models.TextField(blank=True, default='[]')),
                ('tabs_data', models.TextField(blank=True, default='[]')),
                ('cookie_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('last_used_timestamp', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='devices.savedprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('model_code', models.CharField(max_length=100)),
                ('android_version', models.IntegerField(default=14)),
                ('soc', models.CharField(max_length=150)),
                ('webgl_vendor', models.CharField(max_length=100)),
                ('webgl_renderer', models.CharField(max_length=150)),
                ('ram_gb', models.IntegerField(default=8)),
                ('cpu_cores', models.IntegerField(default=8)),
                ('screen_width', models.IntegerField(default=384)),
                ('screen_height', models.IntegerField(default=854)),
                ('dpr', models.FloatField(default=2.8125)),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='devices.savedprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(default='DIRECT', max_length=20)),
                ('proxy_host', models.CharField(blank=True, default='', max_length=255)),
                ('proxy_port', models.IntegerField(default=0)),
                ('proxy_user', models.CharField(blank=True, default='', max_length=100)),
                ('encrypted_password', models.CharField(blank=True, default='', max_length=255)),
                ('web_rtc_mode', models.CharField(blank=True, default='Mdns', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_config', to='devices.savedprofile')),
            ],
        ),
    ]
