# Generated by Django 6.1.1 on 2026-09-12 06:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_savedprofile_proxy_pass_browserstorage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_sync_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('platform', models.CharField(default='ANDROID', max_length=50)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], db_index=True, default='ONLINE', max_length=30)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['owner', 'status'], name='devices_dev_owner_i_d9e88d_idx'), models.Index(fields=['device_id', 'status'], name='devices_dev_device__5f1be1_idx')],
            },
        ),
    ]
