# Generated by Django 5.2.17 on 2026-09-13 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device'),
        ('executions', '0005_executionplan_execution_automation_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='android_version',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='device',
            name='battery_percent',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='current_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_device', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='device',
            name='geckoview_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='screen_height',
            field=models.IntegerField(default=854),
        ),
        migrations.AddField(
            model_name='device',
            name='screen_width',
            field=models.IntegerField(default=384),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline'), ('DISABLED', 'Disabled'), ('REJECTED', 'Rejected')], db_index=True, default='ONLINE', max_length=30),
        ),
    ]
